# Generated by Django 2.2.13 on 2020-06-07 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8322573b-f2ec-4748-99cd-7e7f1c35fa41'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Paìs',
                'verbose_name_plural': 'Paises',
            },
        ),
    ]
