# Generated by Django 2.2.13 on 2020-06-07 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20200607_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d8cfdded-6ecd-4720-bbb8-a1c6f7340e2d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
