# Generated by Django 2.2.13 on 2020-06-13 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20200613_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default=uuid.UUID('704e1406-15f8-44d6-a176-4c70a1bdb27a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
